Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  IgnoredMethods:
    - Vagrant.configure

Metrics/MethodLength:
  Max: 15

Style/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  Enabled: false
