---
vm_group: ubuntu-test
box: generic/ubuntu2004 # centos/7, generic/rhel7
vms:
  - name: all-settings-example
    enabled: false
    # optional
    hostname: demo-01
    cpus: 2
    memory: 2080
  - name: repo
    enabled: true
  - name: pg-01
    enabled: true
  - name: pg-02
    enabled: false
ssh:
  public_key_path: ~/.ssh/id_rsa.pub
defaults:
  vm:
    cpus: 4
    memory: 2048
settings:
  verbosity: 0
