---
vm_group: ubuntu-test
box: generic/ubuntu2004  # almalinux/8, generic/rocky8, generic/rhel8, generic/ubuntu1804, centos/7, generic/rhel7
vms:
#  - name: all-settings-example
#    ip: 192.168.1.11
#    enabled: false
#    # optional
#    hostname: demo-01
#    cpus: 2
#    memory: 2080
#  - name: repo
#    enabled: true
  - name: vm-01
    ip: 192.168.1.12
    enabled: true
  - name: vm-02
    ip: 192.168.1.13
    enabled: true
ssh:
  public_key_path: ~/.ssh/id_rsa.pub
defaults:
  vm:
    cpus: 2
    memory: 2048
settings:
  verbosity: 0
